//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Scribble.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_INSTALL_PROMPT              129
#define IDD_REGISTER                    131
#define ID_PEN_THICK_OR_THIN            32772
#define ID_PEN_WIDTHS                   32773
#define ID_EX_MEMORY                    32778
#define ID_EX_RESOURCE                  32779
#define ID_EX_USER                      32782
#define ID_INSTALLATION_INSTALL         32783
#define ID_INSTALL                      32784
#define ID_REMOVE                       32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
