// ChangeValueFrame.hpp
// Header Generated By ViewSoft
// Portions Copyright (c) 1992-1996 ViewSoft, Inc. All Rights Reserved.

#ifdef EOS_STRICT_INCLUDE
  #ifdef CHANGEVALUEFRAME_HPP
    #error file already included
  #endif
#endif

#ifndef CHANGEVALUEFRAME_HPP
#define CHANGEVALUEFRAME_HPP

#ifndef FRAMEWK_HPP
#include <framewk.hpp>
#endif

// classname Don't edit this comment:ChangeValueFrame
// User code for this class is in ChangeValueFrame

/////////////////////////////////////////////////////////////////////////////////
// BEGIN >>>>>> User pre-declaration code. Don't edit this comment.
// END >>>>>>>> User pre-declaration code. Don't edit this comment.
/////////////////////////////////////////////////////////////////////////////////

EOS_DECLARE_REF(ChangeValueFrame,EosFramework)
#undef ChangeValueFrameRef
#define ChangeValueFrameRef EosRefObj<ChangeValueFrame>

class ChangeValueFrame: public EosFramework
/////////////////////////////////////////////////////////////////////////////////
// BEGIN >>>>>> User More Superclasses code. Don't edit this comment.
// END >>>>>>>> User More Superclasses code. Don't edit this comment.
/////////////////////////////////////////////////////////////////////////////////
{
/////////////////////////////////////////////////////////////////////////////////
// BEGIN >>>>>> User code at the beginning of the class. Don't edit this comment.
// END >>>>>>>> User code at the beginning of the class. Don't edit this comment.
/////////////////////////////////////////////////////////////////////////////////
public:
	ChangeValueFrame();
	ChangeValueFrame(const ChangeValueFrame& src);
	virtual ~ChangeValueFrame();
	ChangeValueFrame& operator =(const ChangeValueFrame& src);
	public: void add();
	public: void subtract();
	public: EosInt value;
public:
	EOS_GET_SDO(ChangeValueFrame)
	EOS_SET_EQUALTO(ChangeValueFrame)
/////////////////////////////////////////////////////////////////////////////////
// BEGIN >>>>>> User code at the end of the class. Don't edit this comment.
// END >>>>>>>> User code at the end of the class. Don't edit this comment.
/////////////////////////////////////////////////////////////////////////////////
};

#define CONNECT_ChangeValueFrame()

EOS_IMPL_REF_HEADER(ChangeValueFrame,EosFramework)

/////////////////////////////////////////////////////////////////////////////////
// BEGIN >>>>>> User post-declaration code. Don't edit this comment.
// END >>>>>>>> User post-declaration code. Don't edit this comment.
/////////////////////////////////////////////////////////////////////////////////

#endif //CHANGEVALUEFRAME_HPP
