// ChatPerson.hpp
// Header Generated By ViewSoft
// Portions Copyright (c) 1992-1996 ViewSoft, Inc. All Rights Reserved.

#ifdef EOS_STRICT_INCLUDE
  #ifdef CHATPERSON_HPP
    #error file already included
  #endif
#endif

#ifndef CHATPERSON_HPP
#define CHATPERSON_HPP

// classname Don't edit this comment:ChatPerson
// User code for this class is in ChatPerson

/////////////////////////////////////////////////////////////////////////////////
// BEGIN >>>>>> User pre-declaration code. Don't edit this comment.
// END >>>>>>>> User pre-declaration code. Don't edit this comment.
/////////////////////////////////////////////////////////////////////////////////

EOS_DECLARE_REF(ChatPerson,EosObject)
#undef ChatPersonRef
#define ChatPersonRef EosRefObj<ChatPerson>

class ChatPerson: public EosObject
/////////////////////////////////////////////////////////////////////////////////
// BEGIN >>>>>> User More Superclasses code. Don't edit this comment.
// END >>>>>>>> User More Superclasses code. Don't edit this comment.
/////////////////////////////////////////////////////////////////////////////////
{
/////////////////////////////////////////////////////////////////////////////////
// BEGIN >>>>>> User code at the beginning of the class. Don't edit this comment.
// END >>>>>>>> User code at the beginning of the class. Don't edit this comment.
/////////////////////////////////////////////////////////////////////////////////
public:
	ChatPerson();
	ChatPerson(const ChatPerson& src);
	virtual ~ChatPerson();
	ChatPerson& operator =(const ChatPerson& src);
	public: void send();
	public: EosPrimitiveArrayRef<EosString> fChatList;
	public: EosString fName;
	public: EosString fSendString;
public:
	EOS_GET_SDO(ChatPerson)
	EOS_SET_EQUALTO(ChatPerson)
/////////////////////////////////////////////////////////////////////////////////
// BEGIN >>>>>> User code at the end of the class. Don't edit this comment.
public:
	ChatPerson(EosPrimitiveArray<EosString> *chatList);
// END >>>>>>>> User code at the end of the class. Don't edit this comment.
/////////////////////////////////////////////////////////////////////////////////
};

#define CONNECT_ChatPerson()

EOS_IMPL_REF_HEADER(ChatPerson,EosObject)

/////////////////////////////////////////////////////////////////////////////////
// BEGIN >>>>>> User post-declaration code. Don't edit this comment.
// END >>>>>>>> User post-declaration code. Don't edit this comment.
/////////////////////////////////////////////////////////////////////////////////

#endif //CHATPERSON_HPP
