//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Mtree.rc
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG1                     102
#define IDC_TREECTL                     1000
#define IDC_DESELECTALL                 1001
#define IDC_SELECTALL                   1002
#define IDC_SHOWSEL                     1003
#define IDC_EDIT1                       1004
#define IDC_ADD                         1005
#define IDC_INSERT                      1006
#define IDC_DELETE                      1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
