//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CoolBar.rc
//
#define IDI_MAINICON                    100
#define IDM_MAINMENU                    101
#define IDB_LOGO                        102
#define IDB_BACKGROUND                  103
#define IDM_ABOUT                       1000
#define IDM_EXIT                        1001
#define IDD_ABOUTBOX                    1002
#define IDM_TOP                         1003
#define IDM_LEFT                        1004
#define IDM_RIGHT                       1005
#define IDM_BOTTOM                      1006
#define IDC_STATIC                      65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         1007
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
