#define IDC_LISTBOX_PROCESSES   101
#define IDC_LISTBOX_THREADS     102
#define IDC_LISTBOX_HEAPS       103
#define IDC_LISTBOX_MODULES     104
#define IDC_PUSHBUTTON_REFRESH  105
#define IDC_STATIC_CPROCESSES   107
#define IDC_STATIC_CTHREADS     106

#define IDC_HEAP_LISTBOX        101
#define IDC_EDIT_BLOCK_DATA     102
