#define IDC_LB_PROCESSES    101
#define IDC_LB_BASIC_INFO   102
#define IDC_LB_MISC 103
#define IDC_LB_QUOTA_LIMITS 104
#define IDC_LB_TIMES    105
#define IDC_LB_VM_COUNTERS  106
#define IDC_LB_POOL_USAGE_AND_LIMITS    107
#define IDC_BUTTON_REFRESH  108
#define IDC_BUTTON_EXIT 109
#define IDC_BUTTON_ABOUT    110
#define IDD_NTQUERYINFORMATIONPROCESS   1

